version: "3.2"
services:
  postgres:
    image: "postgres:13.2-alpine"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ghibli
      - POSTGRES_PASSWORD=ghibli
      - POSTGRES_DB=ghibli
volumes:
  postgres:
